export default {
  first_name: "Monroe",
  last_name: "Izak",
  jobtitle: "Chemical Engineer",
  address: "2nd Floor",
  phone: "174-262-8418",
  email: "mizak0@scribd.com",
  themeColor: "#ff6666",
  summary:
    "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  experience: [
    {title: "Frontend Developer",
    companyName: "Heramandi",
    city: "Pune",
    state: "Bihar",
    startDate: "21 Jan 2020",
    endDate: "22 Jan 2024",
    currentlyWorking: true,
    workSummary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"},
    {title: "Backend Developer",
    companyName: "Google",
    city: "Kolkata",
    state: "Banglore",
    startDate: "May 2021",
    endDate: "Feb 2024",
    currentlyWorking: false,
    workSummary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"},
  ],
  education: [
    {id: "1",
    universityName: "Lovely Professional University",
    startDate: "July 2020",
    endDate: "July 2024",
    degree: "Master",
    major: "Computer Science",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"},
    {id: "2",
    universityName: "St. Geoger's Public School",
    startDate: "July 2018",
    endDate: "July 2020",
    degree: "Senior Secendory",
    major: "Non-Medical",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua"},
  ],
  skills:[
    {
      id:1,
      name: "React",
      rating: 100,
    },
    {
      id:1,
      name: "Git",
      rating: 80,
    },
    {
      id:1,
      name: "NodeJS",
      rating: 90,
    },
    {
      id:1,
      name: "MySql",
      rating: 70,
    },
  ]
};
